//THE STACK AND THE HEAP
// OWNERSHIP
// REFRENCES AND BORROWING
// DANGLING REFRENCES
// SLICE TYPE
// STRING SLICES
// STRING SLICES ARE SLICES
fn main() {
    let s = "Hello,world";
    println!("{}", s);
}
